#!/usr/bin/env bash

# Copyright 2023--2026 Nikita Danilov <danilov@gmail.com>
# See https://github.com/nikitadanilov/t2/blob/master/LICENCE for licencing information.

set -e

echo > config.h
platform="$(uname -srm)"
LDFLAGS="$LDFLAGS -L/usr/local/lib/ -lurcu -lpthread -ldl -lzstd -ltcmalloc -rdynamic -lz"
CC=${CC:-cc}
CXX=${CXX:-c++}
CFLAGS="-I/usr/local/include -march=native -mtune=native -ggdb3 -fno-omit-frame-pointer -foptimize-sibling-calls -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-sign-conversion $CFLAGS"
cc="$($CC -v 2>&1)"
OPTFLAGS="-O6 -Ofast"
distro=unknown
VENV_DIR=".venv"
VENV_PIP="$VENV_DIR/bin/pip"
VENV_PYTHON="$VENV_DIR/bin/python"

function cadd() {
    echo "$*" >> config.h
}

function cundef() {
    sym="$1"
    cadd "#if defined($sym)"
    cadd "#undef $sym"
    cadd "#endif"
}

function cpuflag() {
    :
}

case "$platform" in ####################### Linux #############################
    (*Linux*)
        ROCKSDB_LDFLAGS="-lrocksdb -lsnappy -lz -lbz2 -lzstd -llz4 -ldl -lstdc++"
        LMDB_LDFLAGS="-L/usr/local/lib -llmdb"
        MAP_LDFLAGS="-lstdc++"
        LDFLAGS="$LDFLAGS -lm -latomic -lunwind -luring"
        cadd '#define ON_LINUX  (1)'
        cadd '#define ON_DARWIN (0)'
        cadd '#include "os-linux.h"'
        function cpuflag() {
                flag="$1"
                if command -v lscpu >/dev/null 2>/dev/null ;then
                        lscpu | grep " $flag " >/dev/null 2>/dev/null && echo "-m$flag"
                else
                        cat /proc/cpuinfo | grep " $flag " >/dev/null 2>/dev/null && echo "-m$flag"
                fi
        }
        grep -q Ubuntu /etc/os-release 2>/dev/null && distro=ubuntu
        ;;
esac

case "$platform" in ####################### Linux x86_64 ######################
    (*Linux*x86_64*)
        ;;
esac

case "$platform" in
    (*x86_64*)
        # popcnt for ilog2()
        # No longer needed: cx16 for mag_{get,put}() (128-bit CAS)
        MFLAGS="popcnt"
        ;;
esac

case "$platform" in ####################### Darwin #############################
    (*Darwin*)
        CFLAGS="-I/opt/homebrew/include $CFLAGS"
        LDFLAGS="-L/opt/homebrew/lib $LDFLAGS"
        ROCKSDB_LDFLAGS="-lrocksdb"
        LMDB_LDFLAGS="-L/usr/local/lib -llmdb"
        MAP_LDFLAGS="-lstdc++"
        cadd '#define ON_LINUX  (0)'
        cadd '#define ON_DARWIN (1)'
        cadd '#include "os-darwin.h"'
        function cpuflag() {
                flag="$1"
                sysctl -a | grep machdep.cpu.features | grep -i " $flag " >/dev/null 2>/dev/null && echo "-m$flag"
        }
        distro=darwin
        ;;
esac

case "$platform" in ####################### Darwin x86_64 ######################
    (*Darwin*x86_64*)
        ;;
esac

case "$cc" in (*gcc*13.1.0*)
    CFLAGS="$CFLAGS -Wno-stringop-overflow -Wno-array-bounds"
esac

case "$cc" in (*gcc\ version*)
    cadd '#include "cc-gcc.h"'
esac

case "$cc" in (*clang*)
    cadd '#include "cc-clang.h"'
    OPTFLAGS="-O3 -ffast-math"
    CFLAGS="$CFLAGS -Wno-assume"
    MAP_CFLAGS="$MAP_CFLAGS -std=gnu++11"
esac

for flag in $MFLAGS ;do
    OPTFLAGS="$OPTFLAGS $(cpuflag $flag)"
done

function run() {
    echo "$*"
    "$@"
    rc="$?"
    if [ "$rc" != 0 ]; then
        echo "failed: $rc"
        exit "$rc"
    fi
}

function as_root() {
    if [ "$(id -u)" -eq 0 ] ;then
        "$@"
    elif command -v sudo >/dev/null 2>/dev/null ;then
        sudo "$@"
    else
        echo "Need root privileges to run: $*"
        return 1
    fi
}

function headerp() {
    h="$1"
    f=/tmp/check.h
    echo "#include $h" > "$f"
    cc -E "$f" 2>/dev/null >/dev/null
}

function libp() {
    l="$1"
    f=/tmp/check.c
    echo 'int main(int argc, char **argv) { return 0; }' > "$f"
    cc "$f" -o/tmp/a.out "$l" 2>/dev/null >/dev/null
}

function ensure_venv() {
    if [ ! -x "$VENV_PYTHON" ]; then
        run python3 -m venv "$VENV_DIR"
    fi
    run "$VENV_PYTHON" -m pip install --upgrade pip
}

function setup_prereq_t2() {
    case "$distro" in
        (ubuntu)
            run as_root apt update
            run as_root apt install -y git python3-venv gcc make automake autoconf libtool g++ libunwind-dev google-perftools libgoogle-perftools-dev zstd libzstd-dev liburing-dev libz-dev zlib1g-dev bpfcc-tools bpftrace "linux-headers-$(uname -r)"
            ensure_venv
            run "$VENV_PIP" install tqdm matplotlib numpy
    ;;  (darwin)
            which -s brew
            if [[ $? != 0 ]]; then
                run bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                eval "$(/opt/homebrew/bin/brew shellenv)"
            else
                run brew update
            fi
            run brew install git python automake autoconf libtool gcc gperftools zstd zlib
            ensure_venv
            run "$VENV_PIP" install tqdm matplotlib numpy
    ;;  (*)
            echo "Unknown distro '$distro'"
            exit 1
    esac
}

function setup_prereq_backend() {
    backend="$1"
    case "$distro" in
        (ubuntu)
            case "$backend" in
                (rocksdb)
                    run sudo apt install -y libbz2-dev liblz4-dev libsnappy-dev
            ;;  (lmdb)
                    run sudo apt install -y liblmdb0 liblmdb-dev
            ;;  (map)
                    run sudo apt install -y g++
            esac
    ;;  (darwin)
            case "$backend" in
                (rocksdb)
                    run brew install snappy lz4 bzip2
            ;;  (lmdb)
                    run brew install lmdb
            ;;  (map)
                    run brew install gcc
            esac
    esac
}

function setup_t2() {
    setup_prereq_t2
    headerp '<urcu/urcu-memb.h>' && libp -lurcu || (
        echo "Installing userspace-rcu."
        unset CC CXX CFLAGS LDFLAGS
        run rm -fr userspace-rcu
        run git clone https://git.lttng.org/userspace-rcu.git
        run bash -c 'cd userspace-rcu && ./bootstrap && ./configure && make'
        run sudo make -C userspace-rcu install
        run rm -fr userspace-rcu
    )
}

function setup_backend() {
    backend="$1"
    setup_prereq_backend "$backend"
    case "$backend" in
        (rocksdb)
            headerp '<rocksdb/c.h>' && libp -lrocksdb || (
                echo "Installing rocksdb."
                unset CC CXX CFLAGS LDFLAGS
                run rm -fr rocksdb
                run git clone https://github.com/facebook/rocksdb.git
                run bash -c 'cd rocksdb && DEBUG_LEVEL=0 make shared_lib'
                run sudo make -C rocksdb install-shared install
                run rm -fr rocksdb
            )
    ;;  (lmdb)
            true
    ;;  (map)
            true
    esac
}

function setup_card() {
    setup_prereq_t2
    run "$VENV_PIP" install requests
    [ -d "./card" ] || (
        echo "Installing card."
        run git clone https://github.com/nikitadanilov/card.git
    )
}

function runprep() {
    export LD_LIBRARY_PATH=/usr/local/lib
    run ulimit -n 32000
    run ulimit -c unlimited
    run rm -fr pages log testdb
    run mkdir pages log
    case "$platform" in
        (*Darwin*)
            run as_root sysctl kern.aioprocmax=8192
            run as_root sysctl kern.aiomax=8192
            ;;
    esac
}

function bft() {
    repo_dir=bf-tree-src
    manifest="bftree-bn-adapter/Cargo.toml"
    warn_prefix="bf-tree adapter build skipped:"
    if [ ! -d "$repo_dir" ] ;then
        run git clone https://github.com/microsoft/bf-tree.git "$repo_dir"
        if [ $? != 0 ] ;then
            echo "$warn_prefix cannot clone '$repo_dir'."
            return 0
        fi
    else
        run git -C "$repo_dir" pull --ff-only >/dev/null 2>/dev/null
    fi
    if [ ! -f "$manifest" ] ;then
        echo "$warn_prefix expected local adapter manifest '$manifest' was not found."
        return 0
    fi
    run cargo build --manifest-path "$manifest" --release
    if [ $? != 0 ] ;then
        echo "$warn_prefix cargo build failed."
        return 0
    fi
    case "$platform" in
        (*Darwin*)
            libname=libbftree_bn.dylib
            ;;
        (*)
            libname=libbftree_bn.so
            ;;
    esac
    if [ -f "bftree-bn-adapter/target/release/$libname" ] ;then
        run cp "bftree-bn-adapter/target/release/$libname" "./$libname"
    else
        echo "$warn_prefix expected artifact 'bftree-bn-adapter/target/release/$libname' was not produced."
    fi
}

function usage() {
    echo "Usage: ./build [-d|-f] [-u] [-b] [-c] [-A] [-D SYM] [-o OPTION] [-B BACKEND] [-x]"
    echo "  -B BACKEND  Enable backend: bftree|rocksdb|lmdb|map (can be repeated)"
    echo "  -x          Fast build: skip dependency installation"
}

runut=0
runbn=0
builddocs=0
skipdeps=0
use_rocksdb=0
use_lmdb=0
use_map=0
use_bftree=0

while [ $# != 0 ] ;do
    case "$1" in
        ('-o')
            options="$options $2"
            shift
        ;;  ('-c')
            builddocs=1
        ;;  ('-u')
            runut=1
        ;;  ('-B')
            backend="$2"
            case "$backend" in
                (bftree) use_bftree=1
            ;;  (rocksdb) use_rocksdb=1
            ;;  (lmdb) use_lmdb=1
            ;;  (map) use_map=1
            ;;  (*)
                echo "Unknown backend '$backend'"
                usage
                exit 1
            esac
            shift
        ;;  ('-f')
            options="$options nodebug nocounters opt"
        ;;  ('-d')
            options="$options debug counters noopt profile"
        ;;  ('-D')
            CFLAGS="$CFLAGS -D$2"
            shift
        ;;  ('-b')
            runbn=1
        ;;  ('-A')
            CFLAGS="$CFLAGS -fsanitize=address"
        ;;  ('-x')
            skipdeps=1
        ;;  ('-h'|'--help')
            usage
            exit 0
        ;;  (*)
            echo "Unknown argument $1"
            usage
            exit 1
        ;;
    esac
    shift
done

if [ "$skipdeps" != 1 ]; then
    setup_t2
    [ "$use_bftree" = 1 ] && true
    [ "$use_rocksdb" = 1 ] && setup_backend rocksdb
    [ "$use_lmdb" = 1 ] && setup_backend lmdb
    [ "$use_map" = 1 ] && setup_backend map
    [ "$builddocs" = 1 ] && setup_card
fi

if [ "$builddocs" = 1 ] ; then
    run "$VENV_PYTHON" ./card/card t2.deck
    exit
fi

for o in $options ;do
    case $o in
       (*profile*)
            LDFLAGS="$LDFLAGS -lprofiler"
    ;; (*nodebug*)
            cundef DEBUG
            cadd '#define DEBUG  (0)'
    ;; (*debug*)
            cundef DEBUG
            cadd '#define DEBUG  (1)'
    ;; (*nocounters*)
            cundef COUNTERS
            cadd '#define COUNTERS  (0)'
    ;; (*counters*)
            cundef COUNTERS
            cadd '#define COUNTERS  (1)'
    ;; (*noopt*)
            CFLAGS="$CFLAGS -O0"
    ;; (*opt*)
            CFLAGS="$CFLAGS $OPTFLAGS"
    ;; (*)
            echo "Unknown option '$o'"
            exit 1
    esac
done

git_head=$(git rev-parse HEAD 2> /dev/null || echo "Not a repository.")
md5_sum=$(md5sum t2.c | cut -f1 -d' ')
cc_ver=$($CC -v 2>&1 | tr '\n' ' ')
uname=$(uname -a)

cadd "#define GIT_HEAD \"$git_head\""
cadd "#define MD5_SUM \"$md5_sum\""
cadd "#define CC_VER \"$cc_ver\""
cadd "#define UNAME \"$uname\""
cadd "#define CFLAGS \"$CFLAGS\""
cadd "#define LDFLAGS \"$LDFLAGS\""

run $CC $CFLAGS -DUT=1 -DBN=0 t2.c $LDFLAGS -o ut
run $CC $CFLAGS -DUT=0 -DBN=1 -c t2.c
if [ "$use_rocksdb" = 1 ] ;then
    BN_LDFLAGS="$ROCKSDB_LDFLAGS"
fi
if [ "$use_lmdb" = 1 ] ;then
    BN_LDFLAGS="$BN_LDFLAGS $LMDB_LDFLAGS"
fi
if [ "$use_map" = 1 ] ;then
    run $CXX $MAP_CFLAGS -c map.cpp -o map.o
    BN_LDFLAGS="$BN_LDFLAGS map.o $MAP_LDFLAGS"
fi
BN_CFLAGS="$BN_CFLAGS -DUSE_LMDB=$use_lmdb -DUSE_MAP=$use_map -DUSE_BFTREE=$use_bftree -DUSE_ROCKSDB=$use_rocksdb"
[ $use_bftree == 1 ] && bft
run $CC $CFLAGS $BN_CFLAGS bn.c t2.o $BN_LDFLAGS $LDFLAGS -o bn
if [ "$runut" = 1 ] ; then
    runprep
    run ./ut
fi
if [ "$runbn" = 1 ] ; then
    runprep
    run ./bn -T -h22 -n12 -t14 -N16 -kt2 -f '1*10000000*100:insert$rnd1-6/seq0-20;1*10000000*100:lookup$rnd1-6/20;1*10000000*100:delete$rnd1-6'
fi
